import {
  Building2,
  Boxes,
  Briefcase,
  Car,
  Building,
  Calculator,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  CookingPot,
  ClipboardList,
  Database,
  FileCheck,
  FilePlus,
  FileText,
  Files,
  FolderOpen,
  Fence,
  Fuel,
  Footprints,
  FolderKanban,
  FolderTree,
  Gavel,
  Globe,
  Inbox,
  HandCoins,
  HandHeart,
  HeartHandshake,
  HardHat,
  History,
  Home,
  Hospital,
  Languages,
  Landmark,
  Layers,
  LayoutDashboard,
  Megaphone,
  Map,
  MapPin,
  MapPinned,
  MessageCircleHeart,
  MessageSquare,
  MessagesSquare,
  Milestone,
  Network,
  Handshake,
  Package,
  PackageCheck,
  Percent,
  Pill,
  PackageOpen,
  ScrollText,
  Sparkles,
  Snowflake,
  Route,
  Scale,
  ScanSearch,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  Stamp,
  Store,
  Tags,
  Tent,
  Ticket,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundCog,
  UserRoundCheck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Wheat,
  Newspaper,
  Radio,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  home: Home,
  users: Users,
  'users-round': UsersRound,
  footprints: Footprints,
  tent: Tent,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  'message-square': MessageSquare,
  'message-circle-heart': MessageCircleHeart,
  'messages-square': MessagesSquare,
  inbox: Inbox,
  sparkles: Sparkles,
  'folder-tree': FolderTree,
  settings: Settings,
  send: Send,
  'clipboard-list': ClipboardList,
  database: Database,
  globe: Globe,
  gavel: Gavel,
  fence: Fence,
  'folder-kanban': FolderKanban,
  map: Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  route: Route,
  scale: Scale,
  'scan-search': ScanSearch,
  building: Building,
  'building-2': Building2,
  car: Car,
  boxes: Boxes,
  briefcase: Briefcase,
  'hard-hat': HardHat,
  calculator: Calculator,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'cooking-pot': CookingPot,
  'chart-column': ChartColumn,
  'utensils-crossed': UtensilsCrossed,
  hospital: Hospital,
  fuel: Fuel,
  pill: Pill,
  shield: Shield,
  'shield-alert': ShieldAlert,
  tags: Tags,
  'hand-coins': HandCoins,
  'heart-handshake': HeartHandshake,
  handshake: Handshake,
  history: History,
  'hand-heart': HandHeart,
  landmark: Landmark,
  layers: Layers,
  megaphone: Megaphone,
  milestone: Milestone,
  network: Network,
  languages: Languages,
  package: Package,
  'package-check': PackageCheck,
  percent: Percent,
  'package-open': PackageOpen,
  'scroll-text': ScrollText,
  snowflake: Snowflake,
  stamp: Stamp,
  'file-check': FileCheck,
  'file-plus': FilePlus,
  'file-text': FileText,
  files: Files,
  'folder-open': FolderOpen,
  store: Store,
  ticket: Ticket,
  newspaper: Newspaper,
  radio: Radio,
  'user-round': UserRound,
  wallet: Wallet,
  wheat: Wheat,
}

export function getNavIcon(name: string): LucideIcon {
  return icons[name] ?? LayoutDashboard
}
